version: '3.8'
services:
  database:
    environment:
      POSTGRES_USER: development
      POSTGRES_PASS: secret
      POSTGRES_DBNAME: development
    ports:
      - "5432:5432"
  acme-api:
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
