version: '3.8'
services:
  acme-api:
    image: ${DOCKER_REGISTRY-}acmeapi
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    build:
        context: .
        dockerfile: API/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
        - "database"
  database:
    image: kartoza/postgis:12.0